import AuthProvider from "@/components/provider/AuthProvider";
import Navbar from "@/components/ui/navbar";
import { dbConnect } from "@/lib/mongo";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body className={` antialiased bg-black text-white`}>
        <AuthProvider>
          <Toaster />
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
