import Navbar from "@/components/ui/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased bg-black text-white`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
